### ISSUE TITLE
Support for sphinx-contrib/plantuml

### ISSUE THREAD

**Issue by bosonogi** [sphinx-contrib/sphinxcontrib-confluencebuilder#158]
I was really hoping to use [sphinx-contrib/plantuml](https://github.com/sphinx-contrib/plantuml) together with confluencebuilder to automate publishing UML diagrams to Confluence.

ATM diagrams are included in plain-text to Confluence markup, and it kind of works with this hack:

```rest
.. raw:: confluence

    {code}

.. uml:: foo.uml

.. raw:: confluence

    {code}
```

However many _plantuml_ diagram types do not render correctly as text; eg. links between nodes are missing for deployment diagrams like this one:
```
@startuml

node node1
node node2
node node3
node node4
node node5
node1 -- node2
node1 .. node3
node1 ~~ node4
node1 == node5

@enduml
```

Can you research the amount of effort required to publish these diagrams rendered as images?

If mentoring is an option, I would be willing to get involved.

**Comment by jdknight** [comment]
@bosonogi, sure; I can try to take a gander at this in the future (in a week or so). Thanks for the example set to test against.

I just want to mention that the `master` of this extension has switched to the storage-format over wiki-format (i.e. `{code}` will no longer work in the raw-type). That being said, with the introduced image support to this extension and by quickly glancing at PlatUML's capabilities, I wonder if the image-generated diagrams just work-as-is (speculation).

**Comment by bosonogi** [comment]
@jdknight It did not work outright with master as `ConfluenceTranslator` does not handle `plantuml` nodes. However, I managed to make it work for me with little tweaking — see referenced pull requests.

**Comment by plimanowka** [comment]
Additional change in ConfluenceWriter is required to allow extensions using sphinx.application.Sphinx#add_node register translators for additional node types for confluence output.

Please see changes in #170

**Comment by bosonogi** [comment]
Thanks @plimanowka 👍

**Comment by jessetan** [comment]
An alternative to using sphinx-contrib/plantuml is to place the PlantUML source diagram inside the output and let it be rendered by the PlantUML for Confluence macro https://marketplace.atlassian.com/apps/41025/plantuml-for-confluence

**Comment by bosonogi** [comment]
@jessetan Thanks for the hint. The downside with that approach is that it makes a Sphinx project unusable for any other output format (like PDF or HTML), but when that is not relevant it does look like it would speed up building and publishing significantly.

**Comment by jessetan** [comment]
It would probably need to override the PlantUML extension code if the builder is the confluencebuilder.

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released and it is assumed that the provided translator registry hooks has enabled users to support some level of integration with this extension and plantuml. If this is not the case, please feel free to open up a new issue outlining the specific issue; closing.
