### ISSUE TITLE
curly braces (still) not quoted in all cases

### ISSUE THREAD

**Issue by n2ygk** [sphinx-contrib/sphinxcontrib-confluencebuilder#161]
#41 does not appear to fix all instances of unquoted curly braces. Specifically, using `recommonmark` and a link title that contains curly braces doesn't get quoted and causes the same 500 macro not found error. To reproduce, in a .md file:
```
[See the {json:api} spec](https://jsonapi.org)
```
I assume this applies to RST as well since recommonmark just rewrites MD to RST. Easy enough to reproduce if you need me to.

Also, curly braces are not quoted inside autodoc-generated content that uses the `#:` style of member docstrings:
```python
#: `{json:api} compound document <https://jsonapi.org/format/#document-compound-documents>`_
#: (also used for `related_serializers` for DJA 2.6.0)
included_serializers = {
     'course_terms': 'myapp.serializers.CourseTermSerializer',
}
```
This is OK with `{json:api}` in the comment but flags the `{'course_terms'}` as a macro since the autodoc formats the variable value as one continuous string with no newlines.

See the last line of https://github.com/columbia-it/django-jsonapi-training/blob/master/docs/jsonapi.md for an example of the link behavior and https://github.com/columbia-it/django-jsonapi-training/blob/master/myapp/serializers.py#L73-L77 for the autodoc.

**Comment by n2ygk** [comment]
With `sphinxcontrib-confluencebuilder==0.10.0.dev0` it breaks before even getting to generating any .conf files:

```
File "/Users/alan/src/django-training/env/lib/python3.6/site-packages/sphinxcontrib/confluencebuilder/translator.py", line 269, in visit_enumerated_list
    if node['enumtype'] == 'upperalpha':
  File "/Users/alan/src/django-training/env/lib/python3.6/site-packages/docutils/nodes.py", line 567, in __getitem__
    return self.attributes[key]
KeyError: 'enumtype'
```

**Comment by jdknight** [comment]
@n2ygk, thanks for reporting the issue. I will submit a fix for this.

**Comment by n2ygk** [comment]
@jdknight Please @ mention me when you do and I'll try again. Thanks!

**Comment by jdknight** [comment]
@n2ygk, if you so desire, you can try attempting to test again the `bugfix/ignore-enum-list-style-if-not-set` branch (see also 23a305df8db611c57fa968e74ed89c3c3d4ab59a). This branch should resolve your observed `KeyError: 'enumtype'` issue (speculation).

**Comment by n2ygk** [comment]
@jdknight That appears to have fixed it. Thanks!

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released which addresses the two problems objected in this issue: legacy wiki limitations and enum-type parsing. Marking this issue as closed.
