### ISSUE TITLE
Missing header file

### ISSUE THREAD

**Issue by rcorre** [sphinx-contrib/sphinxcontrib-confluencebuilder#174]
I have a sphinx project created by `sphinx-quickstart` with separate `source` and `build` directories. In `conf.py` I set

```
confluence_header_file = 'confluence_header.tpl'
```

The [docs](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-header-file) say:

> The file path provided should be relative to the build environment’s source directory

So I put the header at `source/confluence_header.tpl`

`make confluence` results in:

```
WARNING: missing header file

The option 'confluence_header_file' has been provided to find a header template
file from a relative location. Ensure the value is set to a proper file path.


sphinxcontrib.confluencebuilder error:
```

When I move the file to the top-level directory (`./confluence_header.tpl`), I get a different error:

```
WARNING: error reading file /home/rodencor/code/olp/dp/workflow/docs/source/confluence_header.tpl: [Errno 2] No such file or directory: '/home/rodencor/code/olp/dp/workflow/docs/source/confluence_header.tp
```

It seems like the confluence builder is looking relative to the source directory at one point, then relative to the top-level at another point. If I run `ln -s source/confluence_header.tpl .
`, then the build succeeds.

**Comment by jdknight** [comment]
Thanks for the report. This appears to be an issue with the configuration check implementation, where it does not take into account the environment source directory (and assumes the working directory is the source directory).

For now, a workaround (aside from the symbolic link example you have provided) would be to provide an absolute path to the header/footer assets (which currently make both the configuration check and translator happy):

    import os
    source_dir = os.path.dirname(os.path.realpath(__file__))
    confluence_header_file = os.path.join(source_dir, 'header.tpl')
    confluence_footer_file = os.path.join(source_dir, 'footer.tpl')

**Comment by rcorre** [comment]
Thanks @jdknight, the workaround worked.

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released which includes the header/footer corrections for relative-provided paths. Marking this issue as closed.
