### ISSUE TITLE
sphinxcontrib-confluencebuilder request error

### ISSUE THREAD

**Issue by keesj** [sphinx-contrib/sphinxcontrib-confluencebuilder#176]
Hi,

I am trying upload a page with an image in it. Somehow this normally works but somehow it currently fails. The image in question is not special and I tried renaming the image or replacing the contents of the image but the problem remains.

After the upload the page contains an image that looks like this
![selection_230](https://user-images.githubusercontent.com/57112/53331874-42795600-38f2-11e9-8b31-2060e6fc2be7.png)

The input rst contains something like
``
.. image:: img/ts3.jpg
``

I am using the git version of the software and confluence Confluence 6.12.2

[log.txt](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/files/2900018/log.txt)

```
writing output... [100%] index                                                                                                                             
publishing documents... [100%] electrical                                                                                                                  
publishing assets... [ 40%] img_ts3.png                                                                                                                    
Exception occurred:
  File "/home/why/.local/lib/python3.6/site-packages/requests/models.py", line 159, in _encode_files
    fdata = fp.read()
AttributeError: 'bool' object has no attribute 'read'
The full traceback has been saved in /tmp/sphinx-err-xru26n0a.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:20: recipe for target 'confluence' failed
make: *** [confluence] Error 2
```

**Comment by keesj** [comment]
More debugging revealed something new. the error occurs when confluence_disable_notifications = True. In such situations the key value pair given to requests/models contains "minorEdit" "True" and this can not be handled with the request module. e.g. it looks like when uploading a file the minor edit is causing problems

```
    fdata = fp.read()
AttributeError: 'bool' object has no attribute 'read'
> /home/why/.local/lib/python3.6/site-packages/requests/models.py(159)_encode_files()
-> fdata = fp.read()
(Pdb) list
154  	                fp = v
155  	
156  	            if isinstance(fp, (str, bytes, bytearray)):
157  	                fdata = fp
158  	            else:
159  ->	                fdata = fp.read()
160  	
161  	            rf = RequestField(name=k, data=fdata, filename=fn, headers=fh)
162  	            rf.make_multipart(content_type=ft)
163  	            new_fields.append(rf)
164  	
(Pdb) fp
True
(Pdb) p k
'minorEdit'
(Pdb) p v
True
(Pdb) quit

```

**Comment by jdknight** [comment]
@keesj, thanks for the find.

Appears to be an issue with older versions of the `requests` library (which we currently "support"). Confirmed seeing the same issue mentioned above with version `2.14.0`. The issue does not appear to be in version `2.21.0`. I can try to investigate (unless anyone else desires) on a compatible way to maintain support with the older versions of requests (or worst, maybe we will need to bump up the dependency version).

For a workaround, one could upgrade the requests package to the most recent version to avoid this issue (at least, observed working in some environments):

```
pip install requests --upgrade
```

**Comment by jdknight** [comment]
Version 1.0 of this extension has been released which includes corrects to support older versions of `requests` (to, at least, v2.14.0). Marking this issue as closed.
